ocean/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 13:01   lzb       1.0         None
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from ocean.views import OceanCalcFbaView, OceanCalcPrivateView, OceanCalcCabinetView

app_name = 'ocean'

urlpatterns = [
    path('fba/', login_required(OceanCalcFbaView.as_view()), name='ocean_fba'),
    path('private/', login_required(OceanCalcPrivateView.as_view()), name='ocean_private'),
    path('cabinet/', login_required(OceanCalcCabinetView.as_view()), name='ocean_cabinet'),

]

users/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
27/04/2021 18:37   lzb       1.0         None
"""

from django.urls import path

from . import views
from .views import RegisterView, LoginView, ForgotPwdView

app_name = 'users'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('forgot-pwd', ForgotPwdView.as_view(), name='forgot_pwd'),

]

users/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User

ROLE_CHOICE = (('DCG', 'DCG'),
               ('CUSTOMER', 'CUSTOMER'),
               )


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    is_validation_email = models.BooleanField(default=False, verbose_name='is_validation_email')   # 是否验证邮件
    telephone = models.CharField('Telephone', max_length=100, blank=True)
    last_update = models.DateTimeField('Last modified', auto_now=True)

    class Meta:
        verbose_name = 'User Profile'
        ordering = ['user__id', ]

    def __str__(self):
        return self.user.__str__()


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=30, verbose_name="Verify Code")
    email = models.EmailField(max_length=50, verbose_name=u"Email")
    send_type = models.CharField(verbose_name="Verify Type",
                                 choices=(("register", "Register"), ("forget", "Forget Password"),
                                          ("update_email", "Modify Email")),
                                 max_length=30)
    one_time_password = models.CharField(max_length=6, verbose_name="One Time Password")
    is_used = models.BooleanField(default=False, verbose_name='is_used')
    send_time = models.DateTimeField(verbose_name="Send Date", auto_now=True)

    class Meta:
        verbose_name = "Email Verify"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)

users/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   forms.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 09:30   lzb       1.0         None
"""

from django import forms
from captcha.fields import CaptchaField
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

from utils.tools import validate_mobile, validate_email
from utils.views import email_check


class LoginForm(forms.Form):
    email = forms.EmailField(required=True, error_messages={"required": _("请输入登录的电子邮件")})
    password = forms.CharField(required=True, min_length=8, error_messages={"required": _("请输入登录密码")})
    captcha = CaptchaField(error_messages={'invalid': _('验证码错误')})


class RegisterForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20, required=True,
                               error_messages={"required": _("请输入用户名")})
    email = forms.CharField(widget=forms.PasswordInput, required=True ,
                            error_messages={"required": _("请输入登录的电子邮件")})
    password1 = forms.CharField(widget=forms.PasswordInput, required=True, error_messages={"required": _("请输入密码")})
    password2 = forms.CharField(widget=forms.PasswordInput, required=True, error_messages={"required": _("请输入密码")})
    agree_term = forms.BooleanField()

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 4:
            raise forms.ValidationError(_("用户名最少需要4个英文字母"))
        elif len(username) > 20:
            raise forms.ValidationError(_("用户名不能太长"))
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError(_("用户名已经存在"))

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError(_("该电子邮件地址已经存在"))
        else:
            raise forms.ValidationError(_("请输入合法的电子邮件地址"))

        return email

    def clean_password1(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError(_('密码长度不能少于8个字符'))
        elif len(password) > 20:
            raise forms.ValidationError(_("密码长度最大为20个字符"))

        return password

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')

        if password and re_password and password != re_password:
            raise forms.ValidationError(_("两次输入的密码不匹配"))

        return re_password


class ForgetPwdForm(forms.Form):
    user_id = forms.CharField(required=True, error_messages={"required": _("请输入电子邮件或手机号")})

    def clean(self):
        user_id = self.data.get('user_id')
        if validate_mobile(user_id):
            filter_result = User.objects.filter(username__exact=user_id)
            if len(filter_result) == 0:
                raise forms.ValidationError(_("输入的手机号码不存在"))
        else:
            if validate_email(user_id):
                filter_result = User.objects.filter(username__exact=user_id)
                if len(filter_result) == 0:
                    raise forms.ValidationError(_("输入的邮箱不存在"))
            else:
                raise forms.ValidationError(_("请输入合法的邮箱或手机号码"))

        return

users/views.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
from captcha.helpers import captcha_image_url
from captcha.models import CaptchaStore
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.utils.translation import gettext as _

from users.forms import LoginForm, RegisterForm, ForgetPwdForm
from users.models import UserProfile
from utils.email_send import send_register_email
from utils.tools import validate_mobile


def index(request):
    return render(request, 'main_menu.html')


# 用户登录
class LoginView(View):
    def get(self, request):
        hash_key = CaptchaStore.generate_key()
        image_url = captcha_image_url(hash_key)
        msg = ''
        login_form = LoginForm()
        return render(request, "login.html", locals())

    def post(self, request):
        login_form = LoginForm(request.POST)
        email = request.POST.get("email", "")
        pass_word = request.POST.get("password", "")
        if login_form.is_valid():
            filter_result = User.objects.filter(email__exact=email)
            username = filter_result[0].username
            user = authenticate(username=username, password=pass_word)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, "login_success.html", locals())
                else:
                    hash_key = CaptchaStore.generate_key()
                    image_url = captcha_image_url(hash_key)
                    msg = _("用户被暂停，请联系系统管理员")
                    return render(request, "login.html", locals())
            else:
                # 图片验证码
                # hashkey验证码生成的秘钥，image_url验证码的图片地址
                hash_key = CaptchaStore.generate_key()
                image_url = captcha_image_url(hash_key)
                msg = _("用户名或者密码错误")
                return render(request, "login.html", locals())
        else:
            hash_key = CaptchaStore.generate_key()
            image_url = captcha_image_url(hash_key)
            msg = _("验证码错误")
            # Python内置了一个locals()函数，它返回当前所有的本地变量字典
            return render(request, "login.html", locals())


# 用户注册(包括手机注册，邮箱注册)
class RegisterView(View):
    def get(self, request):
        register_form = RegisterForm()
        return render(request, "register.html", {"register_form": register_form})

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_name = request.POST.get("email", "")
            pass_word = request.POST.get("password", "")

            if UserProfile.objects.filter(email=user_name):
                return render(request, "register.html", {"register_form": register_form, "msg": "email is existed"})

            send_register_email(user_name, "register",)

            return render(request, "register_mail_success.html")
        else:
            return render(request, "register.html", {"register_form": register_form})


# 忘记密码
class ForgotPwdView(View):
    def get(self, request):
        register_form = RegisterForm()
        return render(request, "forgot_password.html", {"register_form": register_form})

    def post(self, request):
        forget_pwd_form = ForgetPwdForm(request.POST)

        if forget_pwd_form.is_valid():
            user_id = request.POST.get("user_id", "")
            if validate_mobile(user_id):
                # send a new mail for reset password 测试成功
                # send_register_mobile(user_id, "forget", )
                pass
                return redirect('users:login')
            else:
                # send a new mail for reset password 测试成功
                send_register_email(user_id, "forget",)
                # 提示已经发了邮件
                return render(request, "send_resetPwd_success.html")
        else:
            return render(request, "forgot_password.html", {"forgetPwd_form": forget_pwd_form})

users/templates/forgot_password.html
{% extends 'starter.html' %}
{% load static %}
{% load i18n %}
    {% block the_tilte %}{% trans "忘记密码" %}{% endblock %}
    {% block my_link %}
    <!-- Font Icon -->
        <link rel="stylesheet" href="{% static 'register_form/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

        <!-- Main css -->
        <link rel="stylesheet" href="{% static 'register_form/css/style.css' %}">
    {% endblock %}
{% block content %}
    <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form" >
                        {% csrf_token %}
                        <h2 class="form-title">{% trans '找回密码' %}</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="user_id" id="email" placeholder="{% trans '邮件地址或手机号码' %}" required />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="下一步"/>
                        </div>
                    </form>
                    <p class="loginhere">
                        {% trans '我已经是注册用户，' %} <a href="{% url 'users:login' %} " class="loginhere-link">{% trans '登录' %}</a>
                    </p>
                </div>
            </div>
        </section>

    </div>
{% endblock %}
{% block my_script %}
    <script src="{% static 'register_form/js/main.js' %}"></script>
{% endblock %}
<!-- This templates was made by Colorlib (https://colorlib.com) -->

users/templates/login.html
{% extends 'starter.html' %}
{% load i18n %}
{% load static %}
{% load i18n %}
{% block the_tilte %}
    {% trans 'PTP 点达系统|登录' %}
{% endblock %}
{% block content %}
    <div class="hold-transition login-page">
    <div class="login-box">
      <!-- /.login-logo -->
      <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <label class="h4"><b>PTP </b>{% trans "点达系统" %}</label>
        </div>
        <div class="card-body">

          <form action="" method="post">
              {% csrf_token %}
            <div class="input-group mb-3">
              <input type="email" autocomplete="on" class="form-control" name="email"
                     placeholder={% trans "电子邮件" %} value="{{ email }}" required autofocus>
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-envelope"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
              <input type="password" autocomplete="off" class="form-control" name="password"
                     placeholder={% trans "密码" %} required>
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
                <input  type="text" autocomplete="off" id="id_captcha_1" name="captcha_1" maxlength="4"
                        class="form-control col-sm-4" placeholder="{% trans '验证码' %}" style="margin-right: 1px" required>
                <button class='js-captcha-refresh'>
                    <img src="{{ image_url }}" alt="captcha" class="captcha" height="30">
                </button>
                <input id="id_captcha_0" name="captcha_0" type="hidden" value="{{ hash_key }}">
            </div>
            {% if msg %}
                <div>
                     <label class="col-form-label-sm text-danger">{{ msg }}</label>
                </div>
            {% endif %}

            <div class="row">
              <div class="col-8">
              </div>
              <!-- /.col -->
              <div class="col-4">
                <button type="submit" class="js-captcha-refresh btn btn-primary btn-block">{% trans "登录" %}</button>
              </div>
              <!-- /.col -->
            </div>
          </form>

          <p class="mb-1">
            <a href="{% url 'users:forgot_pwd' %}">{% trans "忘记密码" %}</a>
          </p>
          <p class="mb-0">
            <a href="{% url 'users:register' %}" class="text-center">{% trans "注册一个新用户" %}</a>
          </p>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
<!-- /.login-box -->
</div>
{% endblock %}
{% block my_script %}
    <script>
   $('.js-captcha-refresh').click(function() {
      $.getJSON("/captcha/refresh/",
          function (result) {
              $('.captcha').attr('src', result['image_url']);
              $('#id_captcha_0').val(result['key'])
          });
   });
    </script>
{% endblock %}

users/templates/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
    <label>登录成功了！！</label>
</body>
</html>

users/templates/register.html
{% extends 'starter.html' %}
{% load static %}
{% load i18n %}
    {% block the_tilte %}{% trans "注册" %}{% endblock %}
    {% block my_link %}
    <!-- Font Icon -->
        <link rel="stylesheet" href="{% static 'register_form/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

        <!-- Main css -->
        <link rel="stylesheet" href="{% static 'register_form/css/style.css' %}">
    {% endblock %}
{% block content %}
    <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form">
                        {% csrf_token %}
                        <h2 class="form-title">{% trans '新用户注册' %}</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="username" id="username" placeholder="{% trans '用户名' %}" required />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-input" name="email" id="email" placeholder="{% trans '邮件地址' %}" required />
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="password" id="password" placeholder="{% trans '输入密码' %}" required />
                            <span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-input" name="re_password" id="re_password" placeholder="{% trans '重复再输入密码' %}"  />
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="agree_term" id="agree-term" class="agree-term" />
                            <label for="agree-term" class="label-agree-term"><span><span>
                                </span></span>{% trans '我同意点达公司相关的' %}<a href="#" class="term-service text-primary">{% trans '隐私权政策条款' %}</a>{% trans '愿意接受相关来自该公司的相关服务邮件' %}
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="注  册"/>
                        </div>
                    </form>
                    <p class="loginhere">
                        {% trans '我已经是注册用户，' %} <a href="{% url 'users:login' %} " class="loginhere-link">{% trans '登录' %}</a>
                    </p>
                </div>
            </div>
        </section>

    </div>
{% endblock %}
{% block my_script %}
    <script src="{% static 'register_form/js/main.js' %}"></script>
{% endblock %}
<!-- This templates was made by Colorlib (https://colorlib.com) -->

users/templates/register_mail_success.html
{% extends 'warehouse_base.html' %}
{% load static %}
{% block content %}
<h3>We have sent a register mail to your email, please check your email</h3>
<a href="{% url 'users:login' %}">Back to Login</a>
{% endblock %}

users/templates/send_resetPwd_success.html
{% extends 'starter.html' %}
{% block content %}
<h3>We have sent a email to you to reset password, Please check it</h3>
<a href="{% url 'users:login' %}">Back to Login</a>
{% endblock %}