airfreight/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
12/05/2021 14:23   lzb       1.0         None
"""
from django.contrib.auth.decorators import login_required
from django.urls import path

from airfreight.views import AirfreightInquireView

app_name = 'airfreight'

urlpatterns = [
    path('inquire/', AirfreightInquireView.as_view(), name='airfreight_inquire'),

]

ocean/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 13:01   lzb       1.0         None
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from ocean.views import OceanCalcFbaView, OceanCalcPrivateView, OceanCalcCabinetView

app_name = 'ocean'

urlpatterns = [
    path('fba/', login_required(OceanCalcFbaView.as_view()), name='ocean_fba'),
    path('private/', login_required(OceanCalcPrivateView.as_view()), name='ocean_private'),
    path('cabinet/', login_required(OceanCalcCabinetView.as_view()), name='ocean_cabinet'),

]

airfreight/models.py
from django.conf import settings
from django.db import models


# 收货地点
class AirfreightReceiptLocal(models.Model):
    id = models.AutoField(primary_key=True)
    city = models.CharField(max_length=10, null=False, default="", unique=True, verbose_name="city", )
    op_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='op_air_receipt_local',
                                on_delete=models.CASCADE, default=1, verbose_name="Operator")
    op_last_update = models.DateTimeField(auto_now=True, blank=True, verbose_name="Operate Datetime", )

    class Meta:
        db_table = "airfreight_receipt_local"
        verbose_name = "airfreight_receipt_local"
        ordering = ['city', ]

    def __str__(self):
        return '{0}'.format(self.city)


# 空运 postcode 分类 收费列表
class AirfreightPostcodeType(models.Model):
    id = models.AutoField(primary_key=True)
    type_name = models.CharField(max_length=50, null=False, default="", unique=True, verbose_name="en_name", )
    currency = models.CharField(max_length=3, null=False, default="RMB", verbose_name="currency", )
    price = models.DecimalField(blank=True, default=0, max_digits=8, decimal_places=2,
                                verbose_name='price')
    op_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='op_air_postcode_type',
                                on_delete=models.CASCADE, default=1, verbose_name="Operator")
    op_last_update = models.DateTimeField(auto_now=True, blank=True, verbose_name="Operate Datetime", )

    class Meta:
        db_table = "airfreight_postcode_price"
        verbose_name = "airfreight_postcode_price"
        ordering = ['type_name', ]


# 空运 postcode 分类
class AirfreightPostcode(models.Model):
    id = models.AutoField(primary_key=True)
    postcode_type = models.ForeignKey('AirfreightPostcodeType', to_field='id', verbose_name="postcode_type",
                                      on_delete=models.CASCADE)
    begin_code = models.CharField(max_length=10, null=False, default="", unique=True, verbose_name="begin_code", )
    end_code = models.CharField(max_length=10, null=False, default="", verbose_name="end_code", )
    op_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='op_air_postcode_detail',
                                on_delete=models.CASCADE, default=1, verbose_name="Operator")
    op_last_update = models.DateTimeField(auto_now=True, blank=True, verbose_name="Operate Datetime", )

    class Meta:
        db_table = "airfreight_postcode_detail"
        verbose_name = "ocean_postcode_detail"
        ordering = ['postcode_type', 'begin_code', ]


# 空运费用项目列表
class AirfreightItemPrice(models.Model):
    id = models.AutoField(primary_key=True)
    fee_code = models.CharField(max_length=5, null=False, default="", unique=True, verbose_name="fee_code", )
    en_name = models.CharField(max_length=50, null=False, default="", verbose_name="en_name", )
    cn_name = models.CharField(max_length=50, null=False, default="", verbose_name="cn_name", )
    unit = models.CharField(max_length=20, null=False, default="", verbose_name="unit", )
    rate = models.DecimalField(blank=True, default=0, max_digits=8, decimal_places=2,
                               verbose_name='rate')
    currency = models.CharField(max_length=3, null=False, default="RMB", verbose_name="currency", )
    minimum_charge = models.DecimalField(blank=True, default=0, max_digits=8, decimal_places=2,
                                         verbose_name='minimum_charge')
    fee_type = models.IntegerField(default="0", verbose_name="fee_type", )  # 费用类型 0 - 固定费用， 1 - 附加费用
    remark = models.CharField(max_length=100, default="", blank=True, null=True, verbose_name="remark", )
    op_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='op_airfreight_item_price',
                                on_delete=models.CASCADE, default=1, verbose_name="Operator")
    op_last_update = models.DateTimeField(auto_now=True, blank=True, verbose_name="Operate Datetime", )

    class Meta:
        db_table = "airfreight_item_price"
        verbose_name = "airfreight_item_price"
        ordering = ['en_name', ]


# 空运收费列表
class AirfreightPrice(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=5, null=False, default="", verbose_name="code", )
    receipt_area = models.ForeignKey('AirfreightReceiptLocal', to_field='id', related_name='op_airfreight_receipt',
                                     on_delete=models.CASCADE, default=1, verbose_name="receipt_area")
    en_name = models.CharField(max_length=50, null=False, default="", verbose_name="en_name", )
    cn_name = models.CharField(max_length=50, null=False, default="", verbose_name="cn_name", )
    currency = models.CharField(max_length=3, null=False, default="RMB", verbose_name="currency", )
    min_weight = models.DecimalField(blank=True, default=0, max_digits=8, decimal_places=2,
                                     verbose_name='min_weight')
    max_weight = models.DecimalField(blank=True, default=0, max_digits=8, decimal_places=2,
                                     verbose_name='max_weight')
    price = models.DecimalField(blank=True, default=0, max_digits=8, decimal_places=2,
                                verbose_name='price')
    fee_type = models.IntegerField(default="0", verbose_name="fee_type", )  # 费用类型 0 - 固定费用， 1 - 附加费用
    remark = models.CharField(max_length=100, default="", blank=True, null=True, verbose_name="remark", )
    op_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='op_airfreight_price',
                                on_delete=models.CASCADE, default=1, verbose_name="Operator")
    op_last_update = models.DateTimeField(auto_now=True, blank=True, verbose_name="Operate Datetime", )

    class Meta:
        db_table = "airfreight_price"
        verbose_name = "airfreight_price"
        ordering = ['code', ]
        unique_together = ('code', 'receipt_area')

airfreight/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   forms.py.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Description
------------      -------    --------    -----------
17/05/2021 08:24   lzb       1.0         空运部分的forms
"""
from django import forms


class AirFreightForm(forms.Form):
    fab_code = forms.CharField(required=False)
    postcode = forms.CharField(required=False)
    hs_code_number = forms.IntegerField(required=True, )
    volume = forms.DecimalField(required=True)
    weight = forms.DecimalField(required=True)

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

    def clean_volume(self):
        volume = float(self.cleaned_data.get('volume'))
        if volume <= 0:
            raise forms.ValidationError('输入的体积数量必须大于0.')
        return volume

    def clean_weight(self):
        weight = float(self.cleaned_data.get('weight'))
        if weight <= 0:
            raise forms.ValidationError('输入的重量数量必须大于0.')
        return weight

airfreight/views.py
import datetime

from django.shortcuts import render


# Create your views here.
# 海运整柜费用查询
from django.views import View
from django.utils.translation import gettext as _

from airfreight.forms import AirFreightForm
from airfreight.models import AirfreightReceiptLocal, AirfreightPrice, AirfreightPostcode, AirfreightPostcodeType, \
    AirfreightItemPrice
from ocean.calculation import get_quote_ref_no
from ocean.models import AmazonPriceModel, ExchangeModel
from utils.tools import format_postcode


class AirfreightInquireView(View):
    def get(self, request):
        amazon_warehouse = AmazonPriceModel.objects.all()
        receipt_area = AirfreightReceiptLocal.objects.all()
        context = {'amazon_warehouse': amazon_warehouse,
                   'receipt_area': receipt_area,
                   }
        return render(request, 'airfreight_inquire.html', context=context, )

    def post(self, request):
        forms = AirFreightForm(request.POST)
        error_string = ""
        if forms.data['delivery_warehouse'] == 'fba':
            if forms.data['fba_code'] == '':
                error_string = _("必须选择派送的FBA仓点")
        else:
            if forms.data['postcode'] == '':
                error_string = _("必须输入需要派送的英国邮编")
            else:
                # 检查是否是合法的英国postcode
                pass

        context = {'forms': 'forms', 'error_string': error_string}
        if forms.is_valid() and not error_string:
            context['air_result'] = calc_airfreight(request, forms)

            return render(request, 'airfreight_quotation.html', context=context, )

        amazon_warehouse = AmazonPriceModel.objects.all()
        receipt_area = AirfreightReceiptLocal.objects.all()
        context = {'amazon_warehouse': amazon_warehouse,
                   'receipt_area': receipt_area,
                   }
        return render(request, 'airfreight_inquire.html', context=context, )


# 判断体积重
def get_weight(weight, volume):
    # 重量和体积比例是w / m = 167:1, 即体积 * 167和实重对比，wm计算值取较大的这一个
    calc_weight = volume * 167
    if calc_weight > weight:
        calc_weight = weight
    if calc_weight < 45:   # 最低计费重量为45kg起
        calc_weight = 45
    return calc_weight


def calc_airfreight(request, forms):
    air_result = {'total_amount': 0}
    # 获取体积重
    air_result['weight'] = float(forms.data['weight'])
    air_result['volume'] = float(forms.data['volume'])
    air_result['calc_weight'] = get_weight(air_result['weight'], air_result['volume'])
    # 获取空运费的单价
    receipt_area = int(forms.data['receipt_area'])
    price_queryset = AirfreightPrice.objects.filter(receipt_area=receipt_area,
                                                    fee_type=1,
                                                    min_weight__lte=air_result['calc_weight'],
                                                    max_weight__gte=air_result['calc_weight'],
                                                    )
    air_price = 0
    if price_queryset:
        air_price = price_queryset[0].price

    postcode = format_postcode(forms.data['postcode'])
    # 是否非FBA地址
    no_fba_fee = 0
    if forms.data['delivery_warehouse'] == 'no_fba':
        # 需要判断 postcode 是否属于 1区， 2区， 还是中心区
        short_postcode = postcode[:-3].strip()
        queryset_london = AirfreightPostcode.objects.filter(begin_code__lte=short_postcode,
                                                            end_code__gte=short_postcode,
                                                            )
        if queryset_london:
            postcode_type = queryset_london[0].postcode_type.type_name
            if postcode_type == 'ZONE2':
                postcode_type_name = 'ZONE2'
            else:
                postcode_type_name = 'LONDON'
        else:
            postcode_type_name = 'ZONE1'
        no_fba_fee = AirfreightPostcodeType.objects.filter(type_name__exact=postcode_type_name)[0].price

    descriptions_magnetic = _('不带磁')
    # 是否带磁
    try:
        magnetic_fee = 0
        if forms.data['magnetic'] == 'on':
            magnetic_fee = AirfreightPrice.objects.filter(code__exact='Magne').first().price
            descriptions_magnetic = _('带磁')
    except:
        magnetic_fee = 0

    # 是否带电
    descriptions_electricity = _('不带电')
    try:
        electricity_fee = 0
        if forms.data['electricity'] == 'on':
            electricity_fee = AirfreightPrice.objects.filter(code__exact='Elect').first().price
            descriptions_electricity = _('带电')
    except:
        electricity_fee = 0

    # 是否有部分液体
    descriptions_liquid = _('不含有液体')
    try:
        liquid_fee = 0
        if forms.data['liquid'] == 'on':
            liquid_fee = AirfreightPrice.objects.filter(code__exact='Liqui').first().price
            descriptions_liquid = _('含部分液体')
    except:
        liquid_fee = 0

    air_result['other_desc'] = descriptions_magnetic + ',' + descriptions_electricity + ',' + descriptions_liquid

    # 空运费的单价及费用
    air_result['air_price'] = air_price + no_fba_fee + magnetic_fee + electricity_fee + liquid_fee
    air_result['airfreight_fee'] = air_result['air_price'] * air_result['calc_weight']
    air_result['total_amount'] += air_result['airfreight_fee']

    # 需要报关品种的数量
    air_result['hs_code_number'] = int(forms.data['hs_code_number'])
    # 获取附加费的单价
    air_result['export_custom'] = air_result['export_custom_extra'] = 0
    air_result['import_custom'] = air_result['import_custom_extra'] = 0
    air_result['export_custom_unit'] = air_result['export_custom_extra_unit'] = ''
    air_result['import_custom_unit'] = air_result['import_custom_extra_unit'] = ''
    air_result['export_custom_extra_total'] = air_result['import_custom_extra_total'] = 0
    item_price_queryset = AirfreightItemPrice.objects.filter(fee_type=2)
    if item_price_queryset:
        for record in item_price_queryset:
            if record.fee_code == 'OUTCU':
                air_result['export_custom'] = record.rate
                air_result['export_custom_unit'] = record.unit
            if record.fee_code == 'OUTEX':
                air_result['export_custom_extra'] = record.rate
                air_result['export_custom_extra_unit'] = record.unit
            if record.fee_code == 'INCU':
                air_result['import_custom'] = record.rate
                air_result['import_custom_unit'] = record.unit
            if record.fee_code == 'INEX':
                air_result['import_custom_extra'] = record.rate
                air_result['import_custom_extra_unit'] = record.unit

    # 国内出口报关费
    air_result['total_amount'] += air_result['export_custom']
    if air_result['hs_code_number'] > 5:
        air_result['export_custom_extra_total'] = (air_result['hs_code_number'] - 5) * air_result['export_custom_extra']
        air_result['total_amount'] += air_result['export_custom_extra_total']

    # 目的地进口报关费
    air_result['total_amount'] += air_result['import_custom']
    if air_result['hs_code_number'] > 5:
        air_result['import_custom_extra_total'] = (air_result['hs_code_number'] - 5) * air_result['import_custom_extra']
        air_result['total_amount'] += air_result['import_custom_extra_total']

    # #  获取汇率
    # qs_exchange_rate = ExchangeModel.objects.first()
    # air_result['exchange_rate'] = qs_exchange_rate.exchange_rate
    # air_result['total_rmb'] = air_result['total_amount'] * air_result['exchange_rate']

    # 获取编号及时间
    air_result['quote_ref_no'] = get_quote_ref_no(request, 'A')
    air_result['quote_time'] = datetime.datetime.strftime(datetime.datetime.now(), "%Y%m%d %H:%M:%S")

    return air_result

airfreight/templates/airfreight_inquire.html
{% extends 'starter.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="panel-body">
    <div class="tab-content">
        <form class="" id="quoteForm" method="post" action="" >
            {% csrf_token %}
            <div class="col-lg-6">
                <div class="form-group">
                    <label for="port">请选择送货地点：</label>
                </div>
                <label id="receipt_area">
                    <select id="receipt_area" name="receipt_area" class="form-control" style="margin-right: 50px" >
                        {% for receipt in receipt_area %}
                            <option value= {{ receipt.id }}
                                    {% if receipt.id == warehouse_data.0.0 %}
                                        selected
                                    {% endif %}>
                                {{ receipt.city }}
                            </option>
                        {% endfor %}
                    </select>
                </label>
                <div class="form-group">
                    <label for="port">请选择目的地</label>
                </div>
                <div class="form-group">
                    <input type="radio" id="fba_warehouse" name="delivery_warehouse" value="fba" onclick="radio_check()" checked  />
                    <label type="text" > FAB 仓点</label>
                    <label id="warehouse_id">
                    <select id="fba_code" name="fba_code" class="form-control" style="margin-right: 50px" searchable>
                        <option value= "{% if warehouse_data.0.0 == '' %}{{ warehouse_data.0.0 }}{% endif %}">选择需要派送的仓库代码</option>
                        {% for amazon in amazon_warehouse %}
                            <option value= {{ amazon.amazon }}
                                    {% if amazon.amazon.fba_code == warehouse_data.0.0 %}
                                        selected
                                    {% endif %}>
                                {{ amazon.amazon.fba_code }}
                            </option>
                        {% endfor %}
                    </select>
                    </label>
                </div>
                <div class="form-group">
                    <input type="radio" id="no_fba_warehouse" name="delivery_warehouse" value="no_fba" onclick="radio_check()"><label type="text">非FAB 仓点</label>
                    <label id="uk_postcode" style="display: none">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;请输入英国派送地址邮编(Postcode)</label><label>
                    <input class="form-control" id="postcode" name="postcode" maxlength="8" minlength="4"
                           value="{{ forms.data.postcode }}" placeholder="postcode" type="text"
                           style="text-transform: uppercase; display: none" />
                    {% if forms.errors.postcode.data.0.message %}
                        <label id="postcode_fail" class="text-danger">{{ forms.errors.postcode.data.0.message }}</label>
                    {% endif %}
                    </label>
                </div>
                <div class="form-group">
                    <label>体积（立方米）</label>
                    <label>
                    <input class="form-control" id="volume" name="volume" maxlength="8"
                           value="{{ forms.data.postcode }}" placeholder="体积" type="text"
                           style="text-transform: uppercase"
                           oninput="limit_Decimal_2(this)" required />
                    {% if forms.errors.postcode.data.0.message %}
                        <label id="volume_fail" class="text-danger">{{ forms.errors.volume.data.0.message }}</label>
                    {% endif %}
                    </label>
                </div>
                <div class="form-group">
                    <label>重量（公斤）</label>
                    <label>
                    <input class="form-control" id="weight" name="weight"
                           value="{{ forms.data.postcode }}" placeholder="重量" type="text"
                           style="text-transform: uppercase" oninput="limit_Decimal_2(this)" required />
                    {% if forms.errors.weight.data.0.message %}
                        <label id="weight_fail" class="text-danger">{{ forms.errors.weight.data.0.message }}</label>
                    {% endif %}
                    </label>
                </div>
                <div class="form-group">
                    <label >清关HS Code 数量</label>
                <label>
                    <input class=" form-control " id="hs_code_number" name="hs_code_number"
                           value="{{ forms.data.hs_code_number }}" placeholder="HS Code数量" type="text"
                           onkeyup="this.value=this.value.replace(/\D|^0/g,'')"
                           onafterpaste="this.value=this.value.replace(/\D|^0/g,'')" required />
                    {% if forms.errors.hs_code_number.data.0.message %}
                        <label id="hs_code_number_fail" class="text-danger">{{ forms.errors.hs_code_number.data.0.message }}</label>
                    {% endif %}
                </label>
                </div>
                <div class="form-group">
                    <input type="checkbox" id="magnetic" name="magnetic"><label type="text"> 带磁</label>
                    <input type="checkbox" id="electricity" name="electricity"><label type="text"> 带电</label>
                    <input type="checkbox" id="liquid" name="liquid"><label type="text"> 部分带液体（纯液体类，电池类不收）</label>
                </div>
                <div class="form-group">
                    <input type="checkbox" id="pva" name="pva"><label type="text"> 清关是否做PVA递延</label>
                </div>
                <div class="form-group">
                    <input type="checkbox" id="tax" name="tax"><label type="text"> 税金是否预付</label>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">开始询价</button>
                </div>
            </div>
        </form>
    </div>
</div>
    <!-- /form-panel -->
{% endblock %}
{% block my_script %}
    <script type="text/javascript">
        //如果有输入， 清除错误提示
         $("#postcode").bind('input propertychange', function () {
             $('#postcode_fail').html('')
         })

         $("#hs_code_number").bind('input propertychange', function () {
             $('#hs_code_number_fail').html('')
         })

         $("#volume").bind('input propertychange', function () {
             $('#volume_fail').html('')
        })

         $("#weight").bind('input propertychange', function () {
             $('#weight_fail').html('')
         })

    var pathTypeArr = document.getElementsByName("dest");
    function radio_check()
      {
        if (document.getElementById("fba_warehouse").checked) {
            document.getElementById('warehouse_id').style.display='';
            document.getElementById('uk_postcode').style.display='none';
            document.getElementById('postcode').style.display='none';
        }
        if (document.getElementById("no_fba_warehouse").checked) {
            document.getElementById('warehouse_id').style.display='none';
            document.getElementById('uk_postcode').style.display='';
            document.getElementById('postcode').style.display='';
        }
      }

    </script>
{% endblock %}

airfreight/templates/airfreight_quotation.html
{% extends 'starter.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <!--main content start-->
<div class="">
    <div class="invoice-body">
        <div class="pull-left">
          <h2>空运询价单</h2>
        </div>
        <!-- /pull-left -->
        <div class="pull-right ">
            <img src="{% static 'images/dd_logo.png' %}" alt="点达科技", width="200px" height="80px">
        </div>
        <!-- /pull-right -->
        <div class="clearfix"></div>
        <br>
        <div class="row">
            <div class="col-md-9">
                <h4>询价数据</h4>
                <address>
                    送货地：<strong>{{ input_data.port }}</strong><br>
                    目的地：<strong>{{ input_data.port }}</strong><br>
                    清关HS Codes数量： <strong>{{ air_result.hs_code_number }}</strong><br>
                    体积： <strong>{{ air_result.volume|floatformat:2 }} 立方米</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    重量： <strong>{{ air_result.weight|floatformat:2 }} 公斤</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    计费重量：<strong>{{ air_result.calc_weight|floatformat:2  }} 体积重</strong><br>
                    货品说明： <strong>{{ air_result.other_desc }}</strong><br>
                    清关说明：<strong>做PVA递延/不做PVA递延{{ air_result.total_pallets }}</strong><br>
                </address>
          </div>
          <!-- /col-md-9 -->
          <div class="col-md-3">
            <div>
                <!-- /col-md-3 -->
                <div class="pull-left"> 询价编号: </div>
                <div class="text-right">{{ air_result.quote_ref_no }}</div>
                <div class="pull-left"> 询价时间: </div>
                <div class="text-right">{{ air_result.quote_time }}</div>
                <div class="clearfix"></div>
            </div>
            <!-- /row -->
            <br>
            <div class="well well-small green">
                <div class="pull-left"> 费用总计 : </div>
                <div class="pull-right">￥{{ air_result.total_amount|floatformat:2 }}</div>
                <div class="clearfix"></div>
            </div>
          </div>
          <!-- /invoice-body -->
        </div>
        <!-- /col-lg-10 -->
        <table class="table">
          <thead>
            <tr>
              <th style="width:5%" class="text-center">序号</th>
              <th style="width:25%" class="text-left">收费项目</th>
              <th style="width:40%" class="text-left">备注说明</th>
              <th style="width:10%" class="text-left">计价单位</th>
              <th style="width:8%" class="text-right">单价</th>
              <th style="width:12%" class="text-right">金额</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-center">1</td>
              <td>空运费(Customs Clearance)</td>
              <td class="text-left">货品说明：{{ air_result.other_desc }}</td>
              <td class="text-left">KG</td>
              <td class="text-right">￥{{ air_result.air_price|floatformat:2 }}</td>
              <td class="text-right">￥{{ air_result.airfreight_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">2</td>
              <td>国内出口报关费(Extra Codes Surcharge)</td>
              <td class="text-left">此费费用，含五个品名的费用</td>
              <td class="text-left">{{ air_result.export_custom_unit }}</td>
              <td class="text-right">￥{{ air_result.export_custom|floatformat:2 }}</td>
              <td class="text-right">￥{{ air_result.export_custom|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">3</td>
              <td>国内出口报关额外品名附加费(Extra Codes Surcharge)</td>
              <td class="text-left">从第六个品名开始计费</td>
              <td class="text-left">{{ air_result.export_custom_extra_unit }}</td>
              <td class="text-right">￥{{ air_result.export_custom_extra|floatformat:2 }}</td>
              <td class="text-right">￥{{ air_result.export_custom_extra_total|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">4</td>
              <td>目的地进口清关费(Extra Codes Surcharge)</td>
              <td class="text-left">此清关费，含五个品名的费用</td>
              <td class="text-left">{{ air_result.import_custom_unit }}</td>
              <td class="text-right">￥{{ air_result.import_custom|floatformat:2 }}</td>
              <td class="text-right">￥{{ air_result.import_custom|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">5</td>
              <td>目的地进口清关额外品名附加费(Extra Codes Surcharge)</td>
              <td class="text-left">从第六个品名开始计费</td>
              <td class="text-left">{{ air_result.import_custom_extra_unit }}</td>
              <td class="text-right">￥{{ air_result.import_custom_extra|floatformat:2 }}</td>
              <td class="text-right">￥{{ air_result.import_custom_extra_total|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">6</td>
              <td>税金代缴手续费(Use of Deferment)</td>
              <td class="text-left">税金代缴费用为应缴进口duty&VAT的2%， 最低收费 £35.00</td>
              <td class="text-left">{{ air_result.tax_unit }}</td>
              <td class="text-right">￥{{ air_result.tax_price|floatformat:2 }}</td>
              <td class="text-right">￥{{ air_result.tax|floatformat:2 }}</td>
            </tr>
            <tr>
                <td colspan="5" class="text-right no-border">
                    <div class="text-right"><strong>费用合计：</strong></div>
                </td>
              <td class="text-right"><strong>￥{{ air_result.total_amount|floatformat:2 }}</strong></td>
            </tr>
          </tbody>
        </table>
        <h4>其它条款</h4>
        <p>感谢你的支持，本报价为实时报价，价格由于变化比较快，以实际下单为准。</p>
        <br>
        <br>
        <a type="button" id="add_address" href="{% url 'airfreight:airfreight_inquire' %}" class="btn btn-primary pull-left">
            重新查询
        </a>
        <button type="button" class="btn btn-primary pull-right" data-toggle="modal"
                data-target="#myModal-Surcharge" style="float:left; margin-left: 10px">其它费用说明</button>
        <br>
        <br>
    </div>
    <div class="modal fade" id="myModal-Surcharge" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- Modal content-->
            <div class="modal-content">
                {% include 'cabinet/ocean_cabinet_surcharge.html' %}
            </div>
        </div>
{% endblock %}