ocean/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 13:01   lzb       1.0         None
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from ocean.views import OceanCalcFbaView, OceanCalcPrivateView, OceanCalcCabinetView

app_name = 'ocean'

urlpatterns = [
    path('fba/', login_required(OceanCalcFbaView.as_view()), name='ocean_fba'),
    path('private/', login_required(OceanCalcPrivateView.as_view()), name='ocean_private'),
    path('cabinet/', login_required(OceanCalcCabinetView.as_view()), name='ocean_cabinet'),

]

ocean/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   forms.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 13:02   lzb       1.0         None
"""
from django import forms

from ocean.models import UKPostcodeModel
from utils.tools import format_postcode


class FbaQuoteForm(forms.Form):
    port = forms.CharField(required=True)
    hs_code_number = forms.IntegerField(required=True, )
    fba_number = forms.IntegerField(required=True)
    first_delivery = forms.BooleanField(required=False, initial=0)

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

    def clean_fba_number(self):
        fba_number = int(self.cleaned_data.get('fba_number'))
        if fba_number <= 0:
            raise forms.ValidationError('FBA的数量必须大于0.')
        return fba_number


class PrivateQuoteForm(forms.Form):
    port = forms.CharField(required=True)
    hs_code_number = forms.IntegerField(required=True, )
    postcode = forms.CharField(required=True, error_messages={'required': '请填写正确的英国邮编'})
    volume = forms.DecimalField(required=True, )
    weight = forms.DecimalField(required=True, )

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

    def clean_volume(self):
        volume = int(self.cleaned_data.get('volume'))
        if volume <= 0:
            raise forms.ValidationError('体积必须大于0.')
        return volume

    def clean_weight(self):
        weight = int(self.cleaned_data.get('weight'))
        if weight <= 0:
            raise forms.ValidationError('重量必须大于0.')
        return weight

    def clean_postcode(self):
        postcode = self.cleaned_data['postcode'].upper().strip()
        postcode = format_postcode(postcode)

        queryset = UKPostcodeModel.objects.filter(postcode=postcode)

        if not queryset:
            raise forms.ValidationError('输入的邮编不正确，请查证。')
        return postcode


class CabinetQuoteForm(forms.Form):
    port = forms.CharField(required=True)
    hs_code_number = forms.IntegerField(required=True, )

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

ocean/views.py
import datetime

from django.shortcuts import render
from django.views import View
from django.utils.translation import gettext as _

from ocean.forms import FbaQuoteForm, PrivateQuoteForm, CabinetQuoteForm
from ocean.models import OceanPortModel, AmazonPriceModel, FbaItemPriceModel, ContainModel, CabinetItemPriceModel
from ocean.models import PrivateItemPriceModel
from ocean.calculation import calc_bulk_fba, calc_cabinet, judge_cabinet_input, calc_private

MENU_ACTIVE = 'OCEAN'


# 海运散货 FBA
class OceanCalcFbaView(View):
    def get(self, request):
        page_tab = 1
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   }
        return render(request, 'fba/ocean_fba.html', context=context, )

    def post(self, request):
        page_tab = 1
        forms = FbaQuoteForm(request.POST)
        find_error = False
        error_msg = ''
        warehouse_data = []
        warehouse_code_list = []
        for i in range(10):
            code = 'fba_code' + str(i) + '_amsify'
            volume = 'volume' + str(i)
            weight = 'weight' + str(i)
            warehouse_code = request.POST.get(code, 'NO-DATA')
            warehouse_volume = request.POST.get(volume, 'NO-DATA')
            warehouse_weight = request.POST.get(weight, 'NO-DATA')
            # 判断仓库及体积是否均有输入及是否有重复输入的仓库代码
            if warehouse_code == '':
                find_error = True
                error_msg = _('请选择需要派送的亚马逊仓库代码')
                warehouse_data.append([warehouse_code, warehouse_volume, warehouse_weight, ])
            else:
                if warehouse_code != 'NO-DATA' and warehouse_volume != 'NO-DATA':
                    warehouse_data.append([warehouse_code, warehouse_volume, warehouse_weight, ])
                elif warehouse_code == 'NO-DATA' and warehouse_volume == 'NO-DATA':
                    pass
                else:
                    find_error = True
                    error_msg = _('请选择需要派送的亚马逊仓库代码')
                    warehouse_data.append([warehouse_code, warehouse_volume, warehouse_weight, ])

            if warehouse_code in warehouse_code_list:
                find_error = True
                error_msg = _('仓库代码有重复，请检查')
            else:
                if warehouse_code != 'NO-DATA':
                    warehouse_code_list.append(warehouse_code)

        if forms.is_valid() and (not find_error):  # 没有发现错误
            # 开始计算，获取结果
            try:
                first_delivery = forms.data['first_delivery']
            except:
                first_delivery = '0'

            input_data = {'port': forms.data['port'],
                          'hs_code_number': int(forms.data['hs_code_number']),
                          'fba_number': int(forms.data['fba_number']),
                          'first_delivery': first_delivery,
                          'warehouse_data': warehouse_data,
                          }
            # 开始计算，并取到返回的结果
            result_data = calc_bulk_fba(request, input_data)
            all_surcharge = FbaItemPriceModel.objects.filter(fee_type=1)
            context = {'page_tab': page_tab,
                       'menu_active': MENU_ACTIVE,
                       'all_surcharge': all_surcharge,
                       'input_data': input_data,
                       'result_data': result_data
                       }
            return render(request, 'fba/ocean_fba_quotation.html', context=context, )

        # 发现有错误
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()
        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   'warehouse_data': warehouse_data,
                   'forms': forms,
                   'error_msg': error_msg,
                   }
        return render(request, 'fba/ocean_fba.html', context=context, )


# 海运散货私人仓费用查询
class OceanCalcPrivateView(View):
    def get(self, request):
        page_tab = 3
        all_port = OceanPortModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   }
        return render(request, 'private/ocean_private.html', context=context, )

    def post(self, request):
        page_tab = 3
        forms = PrivateQuoteForm(request.POST)
        if forms.is_valid():  # 没有发现错误
            # 开始计算，并取到返回的结果
            result_data = calc_private(request, forms)
            all_surcharge = PrivateItemPriceModel.objects.filter(fee_type=1)
            context = {'page_tab': page_tab,
                       'menu_active': MENU_ACTIVE,
                       'all_surcharge': all_surcharge,
                       'result_data': result_data,
                       }
            return render(request, 'private/ocean_private_quotation.html', context=context, )

        # 发现有错误
        all_port = OceanPortModel.objects.all()
        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'forms': forms,
                   }
        return render(request, 'private/ocean_private.html', context=context, )


# 海运整柜费用查询
class OceanCalcCabinetView(View):
    def get(self, request):
        page_tab = 2
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()
        container_type = ContainModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   'container_type': container_type,
                   }
        return render(request, 'cabinet/ocean_cabinet.html', context=context, )

    def post(self, request):
        page_tab = 2
        forms = CabinetQuoteForm(request.POST)
        result = judge_cabinet_input(request, forms)
        cabinet_data = result[0]
        error_msg = result[1]

        if forms.is_valid() and not error_msg:  # 没有发现错误
            input_data = {'port': forms.data['port'],
                          'hs_code_number': int(forms.data['hs_code_number']),
                          'cabinet_data': cabinet_data,
                          }
            # 开始计算海运整柜，获取结果
            result_data = calc_cabinet(request, input_data)
            all_surcharge = CabinetItemPriceModel.objects.filter(fee_type=1).order_by('id')
            container_type = ContainModel.objects.all()

            context = {'page_tab': page_tab,
                       'menu_active': MENU_ACTIVE,
                       'all_surcharge': all_surcharge,
                       'container_type': container_type,
                       'input_data': input_data,
                       'result_data': result_data
                       }
            return render(request, 'cabinet/ocean_cabinet_quotation.html', context=context, )

        # 发现有整柜输入有错误
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()
        container_type = ContainModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   'container_type': container_type,
                   'cabinet_data': cabinet_data,
                   'forms': forms,
                   'error_msg': error_msg,
                   }
        return render(request, 'cabinet/ocean_cabinet.html', context=context, )

ocean/templates/cabinet/ocean_cabinet_quotation.html
{% extends 'ocean_base.html' %}
{% load static %}
{% block new_content %}
    <!--main content start-->
<div class="">
    <div class="invoice-body">
        <div class="pull-left">
          <h2>海运整柜询价单</h2>
        </div>
        <!-- /pull-left -->
        <div class="pull-right ">
            <img src="{% static 'images/dd_logo.png' %}" alt="点达科技", width="200px" height="80px">
        </div>
        <!-- /pull-right -->
        <div class="clearfix"></div>
        <br>
        <div class="row">
            <div class="col-md-9">
                <h4>询价数据</h4>
                <address>
                    提货地点：<strong>{{ input_data.port }}</strong><br>
                    清关HS Codes数量： <strong>{{ input_data.hs_code_number }}</strong><br>
                    托数(Pallet)合计： <strong>{{ result_data.total_pallets }}</strong><br>
                    集装箱(Container)：<br>
                        <table class="col-lg-6">
                            {% for this_container in input_data.cabinet_data %}
                                <tr>
                                    <td>
                                        {{ forloop.counter }})
                                        {% for container in container_type %}
                                            {% if container.code == this_container.0 %}
                                                {{ container.name }}
                                            {% endif %}
                                        {% endfor %}
                                    </td>
                                    <td>&nbsp;&nbsp;&nbsp;体积：</td>
                                    <td class="text-right"><span >{{ this_container.2|floatformat:2 }} CBM</span></td>
                                    <td>&nbsp;&nbsp;&nbsp;重量：</td>
                                    <td class="text-right"><span class="text-right">{{ this_container.3 }} KG</span></td>
                                    <td>&nbsp;&nbsp;&nbsp;箱数：</td>
                                    <td class="text-right"><span class="text-right">{{ this_container.4 }} CTNs</span></td>
                                </tr>
                            {% endfor %}
                        </table>
                </address>
          </div>
          <!-- /col-md-9 -->
          <div class="col-md-3">
            <div>
                <!-- /col-md-3 -->
                <div class="pull-left"> 询价编号: </div>
                <div class="text-right">{{ result_data.quote_ref_no }}</div>
                <div class="pull-left"> 询价时间: </div>
                <div class="text-right">{{ result_data.quote_time }}</div>
                <div class="clearfix"></div>
            </div>
            <!-- /row -->
            <br>
            <div class="well well-small green">
                <div class="pull-left"> 费用总计 : </div>
                <div class="pull-right">£{{ result_data.total_amount|floatformat:2 }}</div>
                <div class="clearfix"></div>
            </div>
          </div>
          <!-- /invoice-body -->
        </div>
        <!-- /col-lg-10 -->
        <table class="table">
          <thead>
            <tr>
              <th style="width:5%" class="text-center">序号</th>
              <th style="width:25%" class="text-left">收费项目</th>
              <th style="width:40%" class="text-left">备注说明</th>
              <th style="width:10%" class="text-left">计价单位</th>
              <th style="width:8%" class="text-right">单价</th>
              <th style="width:12%" class="text-right">金额</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-center">1</td>
              <td>清关费(Customs Clearance)</td>
              <td class="text-left">此清关费，含三个品名的费用</td>
              <td class="text-left">{{ result_data.customs_clearance_unit }}</td>
              <td class="text-right">£{{ result_data.customs_clearance_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.customs_clearance|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">2</td>
              <td>额外品名附加费(Extra Codes Surcharge)</td>
              <td class="text-left">从第四个品名开始计费</td>
              <td class="text-left">{{ result_data.extra_codes_unit }}</td>
              <td class="text-right">£{{ result_data.extra_codes_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.extra_codes|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">3</td>
              <td>税金代缴手续费(Use of Deferment)</td>
              <td class="text-left">税金代缴费用为应缴进口duty&VAT的2%， 最低收费 £35.00</td>
              <td class="text-left">{{ result_data.tax_unit }}</td>
              <td class="text-right">£{{ result_data.tax_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.tax|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">4</td>
              <td>码头操作费(THC)</td>
              <td class="text-left"></td>
              <td class="text-left">{{ result_data.thc_fee_unit }}</td>
              <td class="text-right">£{{ result_data.thc_fee_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.thc_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">5</td>
              <td>文件费(Document Fee)</td>
              <td class="text-left"></td>
              <td class="text-left">{{ result_data.doc_fee_unit }}</td>
              <td class="text-right">£{{ result_data.doc_fee_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.doc_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">6</td>
              <td>吊柜费(Lift  Container Surcharge)</td>
              <td class="text-left"></td>
              <td class="text-left">{{ result_data.lift_fee_unit }}</td>
              <td class="text-right">£{{ result_data.lift_fee_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.lift_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">7</td>
              <td>设备费(Equipment surcharge)</td>
              <td class="text-left"></td>
              <td class="text-left">{{ result_data.equipment_fee_unit }}</td>
              <td class="text-right">£{{ result_data.equipment_fee_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.equipment_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">8</td>
              <td>码头杂费(Port surcharge)</td>
              <td class="text-left"></td>
              <td class="text-left">{{ result_data.port_fee_unit }}</td>
              <td class="text-right">£{{ result_data.port_fee_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.port_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">9</td>
              <td>提柜至我司海外拆分费(Shunt surcharge)</td>
              <td class="text-left"></td>
              <td class="text-left">{{ result_data.shunt_fee_unit }}</td>
              <td class="text-right">£{{ result_data.shunt_fee_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.shunt_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">10</td>
              <td>打托缠膜费(Palletising & Shrimping)</td>
              <td class="text-left">以每托盘按照1.5立方或500kg（亚马逊托盘承载货物标准）进行预估</td>
              <td class="text-left">{{ result_data.pack_unit }}</td>
              <td class="text-right">£{{ result_data.pack_price|floatformat:2 }}</td>
              <td class="text-right">£{{ result_data.pack_fee|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">11</td>
              <td>卸柜费(Unloading surcharge)</td>
              <td class="text-left">超过1000箱的部分额外加收0.2每箱</td>
              <td class="text-left">{{ result_data.unloading_fee_unit }}</td>
              <td class="text-right"></td>
              <td class="text-right">£{{ result_data.unloading_fee|floatformat:2 }}</td>
            </tr>
            {% for warehouse in result_data.warehouse_data %}
                <tr>
                  <td class="text-center">{{ forloop.counter0|add:"12" }}</td>
                  <td>派送费(Delivery Fee) - 仓库代码：{{ warehouse.0 }}</td>
                    <td class="text-left">体积: {{ warehouse.1 }} 立方米
                        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>重量：{{ warehouse.2 }} 公斤</td>
                  <td class="text-right"></td>
                  <td class="text-right"></td>
                  <td class="text-right">£{{ warehouse.3|floatformat:2 }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="5" class="text-right no-border">
                    <div class="text-right"><strong>费用合计：</strong></div>
                </td>
              <td class="text-right"><strong>£{{ result_data.total_amount|floatformat:2 }}</strong></td>
            </tr>
            <tr>
              <td colspan="3" class="text-right no-border">
                <div><strong></strong>英镑/人民币汇率：¥1.00 = £{{ result_data.exchange_rate|floatformat:4 }}
                    (请注意  该汇率仅作为参考，实际结算汇率以下单当天汇率为准)   </div>
              </td>
                <td colspan="2" class="text-right no-border">
                    <div><strong>人民币合计: </strong></td></div>
              <td class="text-right"><strong>¥{{ result_data.total_rmb|floatformat:2 }}</strong></td>
            </tr>
          </tbody>
        </table>
        <h4>其它条款</h4>
        <p>感谢你的支持，本报价为实时报价，价格由于变化比较快，以实际下单为准。PS: 监管仓堆存费实报实销</p>
        <br>
        <br>
        <a type="button" id="add_address" href="{% url 'ocean:ocean_cabinet' %}" class="btn btn-primary pull-left">
            重新查询
        </a>
        <button type="button" class="btn btn-primary pull-right" data-toggle="modal"
                data-target="#myModal-Surcharge" style="float:left; margin-left: 10px">其它费用说明</button>
        <br>
        <br>
    </div>
    <div class="modal fade" id="myModal-Surcharge" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- Modal content-->
            <div class="modal-content">
                {% include 'cabinet/ocean_cabinet_surcharge.html' %}
            </div>
        </div>
{% endblock %}

ocean/templates/cabinet/ocean_cabinet_reload.html
{% for c_code, c_qty, c_volume, c_weight, c_boxes, c_warehouse in cabinet_data %}
    {% if forloop.counter0 > 0 %}
        <table id="container{{ forloop.counter0 }}_table" class="table">
            <tbody>
            <tr>
                <td width="35%">
                    <select id="container{{ forloop.counter0 }}_code" name="container{{ forloop.counter0 }}_code"
                            value="NO-DATA" class="form-control" style="margin-right: 20px" >
                        {% for container_type in container_type %}
                            <option value= {{ container_type.code }}
                                    {% if container_type.code == c_code %}
                                        selected
                                    {% endif %}>
                                {{ container_type.name }}
                            </option>
                        {% endfor %}
                    </select>
                </td>
                <td width="5%">
                    <input class=" form-control" id="container{{ forloop.counter0 }}_qty" name="container{{ forloop.counter0 }}_qty"
                           value="{{ c_qty }}" placeholder="柜量" type="text"
                           oninput="onlyNumber(this)" readonly />
                </td>
                <td width="20%">
                    <input class=" form-control" id="container{{ forloop.counter0 }}_volume" name="container{{ forloop.counter0 }}_volume"
                           value="{{ c_volume }}" placeholder="体积" type="text"
                           oninput="limit_Decimal_2(this)" required />
                </td>
                <td width="20%">
                    <input class=" form-control" id="container{{ forloop.counter0 }}_weight" name="container{{ forloop.counter0 }}_weight"
                           value="{{ c_weight }}" placeholder="重量" type="text"
                           oninput="limit_Decimal_2(this)" required />
                </td>
                <td width="10%">
                    <input class=" form-control" id="container{{ forloop.counter0 }}_boxes" name="container{{ forloop.counter0 }}_boxes"
                           value="{{ c_boxes }}" placeholder="箱数" type="text"
                           oninput="onlyNumber(this)" required />
                </td>
                <td width="10%">
                    <button type="button" id="add_container", class="btn btn-danger "
                            onclick="deleteContainerRow('#container{{ forloop.counter0 }}_table')">
                        <span class="glyphicon glyphicon-minus-sign"></span>
                        删除集装箱
                    </button>
                </td>
            </tr>
            <tr>
                <td class="control-label text-center"></td>
                <td colspan="5">
                <table id="container{{ forloop.counter0 }}_warehouse_table" class="table">
                    <tbody>
                        {% for w_code, w_volume, w_weight in c_warehouse %}
                            <tr>
                                <td width="42%">
                                    <select id="container{{forloop.parentloop.counter0}}_fba_code{{ forloop.counter0 }}"
                                            name="container{{forloop.parentloop.counter0}}_fba_code{{ forloop.counter0 }}"
                                            class="form-control" style="margin-right: 20px" searchable>
                                        <option value= "{% if w_code %}{{ w_code }}{% endif %}">选择仓库代码</option>
                                        {% for amazon in amazon_warehouse %}
                                            <option value= {{ amazon.amazon }}
                                                {% if amazon.amazon.fba_code == w_code %}
                                                    selected
                                                {% endif %}>
                                                {{ amazon.amazon.fba_code }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td width="20%">
                                    <input class=" form-control" id="container{{forloop.parentloop.counter0}}_volume{{ forloop.counter0 }} "
                                           name="container{{forloop.parentloop.counter0}}_volume{{ forloop.counter0 }}"
                                           value="{{ w_volume }}"
                                           placeholder="Volume" type="text" oninput="limit_Decimal_2(this)" required />
                                </td>
                                <td width="20%">
                                    <input class=" form-control" id="container{{forloop.parentloop.counter0}}_weight{{ forloop.counter0 }} "
                                           name="container{{forloop.parentloop.counter0}}_weight{{ forloop.counter0 }}"
                                           value="{{ w_weight }}"
                                           placeholder="Volume" type="text" oninput="limit_Decimal_2(this)" required />
                                </td>
                                {% if forloop.counter0 == 0 %}
                                    <td width="18%">
                                        <button type="button" id="add_container{{ forloop.parentloop.counter0 }}_warehouse",
                                                class="btn btn-warning " onclick="appendWarehouseRow({{ forloop.parentloop.counter0 }})">
                                            <span class="glyphicon glyphicon-plus-sign"></span>
                                            新增仓库
                                        </button>
                                    </td>
                                {% else %}
                                    <td width="18%">
                                        <button type="button" id="add_container{{forloop.parentloop.counter0}}_warehouse",
                                                class="btn btn-danger " onclick="deleteCurrentRow(this, {{forloop.parentloop.counter0}})">
                                            <span class="glyphicon glyphicon-minus-sign"></span>
                                            删除仓库
                                        </button>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                </td>
            </tr>
            </tbody>
        </table>
    {% endif %}
{% endfor %}

ocean/templates/cabinet/ocean_cabinet_surcharge.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">海运整柜其它费用说明</h4>
</div>
<div class="modal-body">
    <!-- Surcharges Table -->
    <table class="table table-bordered table-striped " >
        <thead>
            <th class="text-center">费用详细</th>
            <th class="text-center">英文名</th>
            <th class="text-center">单位</th>
            <th class="text-center">价格</th>
            <th class="text-center">备注</th>
        </thead>
        <tbody>
            {% for surcharge in all_surcharge %}
                <tr>
                    <td class="">{{ surcharge.cn_name }}</td>
                    <td class="">{{ surcharge.en_name }}</td>
                    <td class="">{{ surcharge.unit }}</td>
                    {% if surcharge.fee_code != 'WASTE' %}
                        <td class="text-right">£{{ surcharge.rate }}</td>
                    {% else %}
                        <td class="text-right">{{ surcharge.rate }}%</td>
                    {% endif %}
                    <td class="text-left">{{ surcharge.remark }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>