ocean/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   urls.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 13:01   lzb       1.0         None
"""

from django.urls import path
from django.contrib.auth.decorators import login_required

from ocean.views import OceanCalcFbaView, OceanCalcPrivateView, OceanCalcCabinetView

app_name = 'ocean'

urlpatterns = [
    path('fba/', login_required(OceanCalcFbaView.as_view()), name='ocean_fba'),
    path('private/', login_required(OceanCalcPrivateView.as_view()), name='ocean_private'),
    path('cabinet/', login_required(OceanCalcCabinetView.as_view()), name='ocean_cabinet'),

]

ocean/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   forms.py    
@Contact :   thomaslzb@hotmail.com
@License :   (C)Copyright 2020-2022, Zibin Li

@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
28/04/2021 13:02   lzb       1.0         None
"""
from django import forms

from ocean.models import UKPostcodeModel
from utils.tools import format_postcode


class FbaQuoteForm(forms.Form):
    port = forms.CharField(required=True)
    hs_code_number = forms.IntegerField(required=True, )
    fba_number = forms.IntegerField(required=True)
    first_delivery = forms.BooleanField(required=False, initial=0)

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

    def clean_fba_number(self):
        fba_number = int(self.cleaned_data.get('fba_number'))
        if fba_number <= 0:
            raise forms.ValidationError('FBA的数量必须大于0.')
        return fba_number


class PrivateQuoteForm(forms.Form):
    port = forms.CharField(required=True)
    hs_code_number = forms.IntegerField(required=True, )
    postcode = forms.CharField(required=True, error_messages={'required': '请填写正确的英国邮编'})
    volume = forms.DecimalField(required=True, )
    weight = forms.DecimalField(required=True, )

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

    def clean_volume(self):
        volume = int(self.cleaned_data.get('volume'))
        if volume <= 0:
            raise forms.ValidationError('体积必须大于0.')
        return volume

    def clean_weight(self):
        weight = int(self.cleaned_data.get('weight'))
        if weight <= 0:
            raise forms.ValidationError('重量必须大于0.')
        return weight

    def clean_postcode(self):
        postcode = self.cleaned_data['postcode'].upper().strip()
        postcode = format_postcode(postcode)

        queryset = UKPostcodeModel.objects.filter(postcode=postcode)

        if not queryset:
            raise forms.ValidationError('输入的邮编不正确，请查证。')
        return postcode


class CabinetQuoteForm(forms.Form):
    port = forms.CharField(required=True)
    hs_code_number = forms.IntegerField(required=True, )

    def clean_hs_code_number(self):
        hs_code_number = int(self.cleaned_data.get('hs_code_number'))
        if hs_code_number <= 0:
            raise forms.ValidationError('HS Code 的数量必须大于0.')
        return hs_code_number

ocean/views.py
import datetime

from django.shortcuts import render
from django.views import View
from django.utils.translation import gettext as _

from ocean.forms import FbaQuoteForm, PrivateQuoteForm, CabinetQuoteForm
from ocean.models import OceanPortModel, AmazonPriceModel, FbaItemPriceModel, ContainModel, CabinetItemPriceModel
from ocean.models import PrivateItemPriceModel
from ocean.calculation import calc_bulk_fba, calc_cabinet, judge_cabinet_input, calc_private

MENU_ACTIVE = 'OCEAN'


# 海运散货 FBA
class OceanCalcFbaView(View):
    def get(self, request):
        page_tab = 1
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   }
        return render(request, 'fba/ocean_fba.html', context=context, )

    def post(self, request):
        page_tab = 1
        forms = FbaQuoteForm(request.POST)
        find_error = False
        error_msg = ''
        warehouse_data = []
        warehouse_code_list = []
        for i in range(10):
            code = 'fba_code' + str(i) + '_amsify'
            volume = 'volume' + str(i)
            weight = 'weight' + str(i)
            warehouse_code = request.POST.get(code, 'NO-DATA')
            warehouse_volume = request.POST.get(volume, 'NO-DATA')
            warehouse_weight = request.POST.get(weight, 'NO-DATA')
            # 判断仓库及体积是否均有输入及是否有重复输入的仓库代码
            if warehouse_code == '':
                find_error = True
                error_msg = _('请选择需要派送的亚马逊仓库代码')
                warehouse_data.append([warehouse_code, warehouse_volume, warehouse_weight, ])
            else:
                if warehouse_code != 'NO-DATA' and warehouse_volume != 'NO-DATA':
                    warehouse_data.append([warehouse_code, warehouse_volume, warehouse_weight, ])
                elif warehouse_code == 'NO-DATA' and warehouse_volume == 'NO-DATA':
                    pass
                else:
                    find_error = True
                    error_msg = _('请选择需要派送的亚马逊仓库代码')
                    warehouse_data.append([warehouse_code, warehouse_volume, warehouse_weight, ])

            if warehouse_code in warehouse_code_list:
                find_error = True
                error_msg = _('仓库代码有重复，请检查')
            else:
                if warehouse_code != 'NO-DATA':
                    warehouse_code_list.append(warehouse_code)

        if forms.is_valid() and (not find_error):  # 没有发现错误
            # 开始计算，获取结果
            try:
                first_delivery = forms.data['first_delivery']
            except:
                first_delivery = '0'

            input_data = {'port': forms.data['port'],
                          'hs_code_number': int(forms.data['hs_code_number']),
                          'fba_number': int(forms.data['fba_number']),
                          'first_delivery': first_delivery,
                          'warehouse_data': warehouse_data,
                          }
            # 开始计算，并取到返回的结果
            result_data = calc_bulk_fba(request, input_data)
            all_surcharge = FbaItemPriceModel.objects.filter(fee_type=1)
            context = {'page_tab': page_tab,
                       'menu_active': MENU_ACTIVE,
                       'all_surcharge': all_surcharge,
                       'input_data': input_data,
                       'result_data': result_data
                       }
            return render(request, 'fba/ocean_fba_quotation.html', context=context, )

        # 发现有错误
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()
        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   'warehouse_data': warehouse_data,
                   'forms': forms,
                   'error_msg': error_msg,
                   }
        return render(request, 'fba/ocean_fba.html', context=context, )


# 海运散货私人仓费用查询
class OceanCalcPrivateView(View):
    def get(self, request):
        page_tab = 3
        all_port = OceanPortModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   }
        return render(request, 'private/ocean_private.html', context=context, )

    def post(self, request):
        page_tab = 3
        forms = PrivateQuoteForm(request.POST)
        if forms.is_valid():  # 没有发现错误
            # 开始计算，并取到返回的结果
            result_data = calc_private(request, forms)
            all_surcharge = PrivateItemPriceModel.objects.filter(fee_type=1)
            context = {'page_tab': page_tab,
                       'menu_active': MENU_ACTIVE,
                       'all_surcharge': all_surcharge,
                       'result_data': result_data,
                       }
            return render(request, 'private/ocean_private_quotation.html', context=context, )

        # 发现有错误
        all_port = OceanPortModel.objects.all()
        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'forms': forms,
                   }
        return render(request, 'private/ocean_private.html', context=context, )


# 海运整柜费用查询
class OceanCalcCabinetView(View):
    def get(self, request):
        page_tab = 2
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()
        container_type = ContainModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   'container_type': container_type,
                   }
        return render(request, 'cabinet/ocean_cabinet.html', context=context, )

    def post(self, request):
        page_tab = 2
        forms = CabinetQuoteForm(request.POST)
        result = judge_cabinet_input(request, forms)
        cabinet_data = result[0]
        error_msg = result[1]

        if forms.is_valid() and not error_msg:  # 没有发现错误
            input_data = {'port': forms.data['port'],
                          'hs_code_number': int(forms.data['hs_code_number']),
                          'cabinet_data': cabinet_data,
                          }
            # 开始计算海运整柜，获取结果
            result_data = calc_cabinet(request, input_data)
            all_surcharge = CabinetItemPriceModel.objects.filter(fee_type=1).order_by('id')
            container_type = ContainModel.objects.all()

            context = {'page_tab': page_tab,
                       'menu_active': MENU_ACTIVE,
                       'all_surcharge': all_surcharge,
                       'container_type': container_type,
                       'input_data': input_data,
                       'result_data': result_data
                       }
            return render(request, 'cabinet/ocean_cabinet_quotation.html', context=context, )

        # 发现有整柜输入有错误
        all_port = OceanPortModel.objects.all()
        amazon_warehouse = AmazonPriceModel.objects.all()
        container_type = ContainModel.objects.all()

        context = {'page_tab': page_tab,
                   'menu_active': MENU_ACTIVE,
                   'all_port': all_port,
                   'amazon_warehouse': amazon_warehouse,
                   'container_type': container_type,
                   'cabinet_data': cabinet_data,
                   'forms': forms,
                   'error_msg': error_msg,
                   }
        return render(request, 'cabinet/ocean_cabinet.html', context=context, )

ocean/templates/fba/ocean_fba.html
{% extends 'ocean_base.html' %}
{#我已经在此文件中引入了JS 和 CSS#}
{#  <link href="{% static 'lzb/css/amsify.select.css' %}" rel="stylesheet">#}
{#  <script href="{% static 'lzb/js/jquery.amsifyselect.js' %}" rel="stylesheet"></script>#}

{% load static %}
{% block new_content %}
<div class="panel-body">
    <div class="tab-content">
        <form class="" id="quoteForm" method="post" action="" >
            {% csrf_token %}
            <div class="col-lg-4">
                <div class="form-group">
                    <label for="port">提货地点（POD）</label>
                    <select name = "port" class="form-control" style="margin-right: 20px">
                    {% for port in all_port %}
                        <option value= "{{ port.port_code }} - {{ port.port_name }}"
                        {% if forms.data.port|slice:"3" == port.port_code %}
                            selected
                        {% endif %}>
                            {{ port.port_code }} - {{ port.port_name }}
                        </option>
                    {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label >清关HS Code 数量</label>
                    <input class=" form-control " id="hs_code_number" name="hs_code_number"
                           value="{{ forms.data.hs_code_number }}" placeholder="HS Code数量" type="text"
                           onkeyup="this.value=this.value.replace(/\D|^0/g,'')" onafterpaste="this.value=this.value.replace(/\D|^0/g,'')"
                           required />
                    {% if forms.errors.hs_code_number.data.0.message %}
                        <label id="hs_code_number_fail" class="text-danger">{{ forms.errors.hs_code_number.data.0.message }}</label>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label>FBA 数量</label>
                    <input class="form-control" id="fba_number" name="fba_number"
                           value="{{ forms.data.fba_number }}" placeholder="FBA 数量" type="text"
                           onkeyup="this.value=this.value.replace(/\D|^0/g,'')" onafterpaste="this.value=this.value.replace(/\D|^0/g,'')"
                           required />
                    {% if forms.errors.fba_number.data.0.message %}
                        <label id="fba_number_fail" class="text-danger">{{ forms.errors.fba_number.data.0.message }}</label>
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="checkbox form-control">
                        <label><input type="checkbox" name="first_delivery" value="1"
                         {% if forms.data.first_delivery == '1' %}checked{% endif %}>
                            头程自行安排在英国监管仓</label>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">开始询价</button>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="form-group">
                    <!-- Amazon Address Table -->
                    <table id="warehouse_table" class="table table-bordered table-striped " >
                        <thead>
                            <tr>
                                <th class="text-center list-group-item-info" width="40%">
                                    亚马孙仓库
                                </th>
                                <th class="text-center list-group-item-info"  width="25%">
                                    体积(立方米)
                                </th>
                                <th class="text-center list-group-item-info"  width="25%">
                                    重量(公斤)
                                </th>
                                <th class="text-center list-group-item-info"  width="10%">
                                    操作
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <select id="fba_code0" name="fba_code0" class="form-control" style="margin-right: 20px" searchable>
                                        <option value= "{% if warehouse_data.0.0 == '' %}{{ warehouse_data.0.0 }}{% endif %}">选择需要派送的仓库代码</option>
                                        {% for amazon in amazon_warehouse %}
                                            <option value= {{ amazon.amazon }}
                                                    {% if amazon.amazon.fba_code == warehouse_data.0.0 %}
                                                        selected
                                                    {% endif %}>
                                                {{ amazon.amazon.fba_code }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td>
                                    <input class=" form-control" id="volume0" name="volume0"
                                           value="{{ warehouse_data.0.1 }}" placeholder="体积" type="text"
                                           oninput="limit_Decimal_2(this)"
                                           required />
                                </td>
                                <td>
                                    <input class=" form-control" id="weight0" name="weight0"
                                           value="{{ warehouse_data.0.2 }}" placeholder="重量" type="text"
                                           oninput="limit_Decimal_2(this)"
                                           required />
                                </td>
                                <td>
                                    <button type="button" id="add_warehouse", class="btn btn-warning " onclick="appendRow()">
                                        <span class="glyphicon glyphicon-plus-sign"></span>
                                        新增仓库
                                    </button>
                                </td>
                            </tr>
                            {% for w_code, w_volume, w_weight in warehouse_data %}
                                {% if forloop.counter0 > 0 %}
                                    <tr>
                                        <td>
                                            <select id="fba_code{{ forloop.counter0 }}" name="fba_code{{ forloop.counter0 }}" class="form-control" style="margin-right: 20px" searchable>
                                                <option value= "{% if w_code == '' %}{{ warehouse_data.0.0 }}{% endif %}">选择需要派送的仓库代码</option>
                                                {% for amazon in amazon_warehouse %}
                                                    <option value= {{ amazon.amazon }}
                                                        {% if amazon.amazon.fba_code == w_code %}
                                                            selected
                                                        {% endif %}>
                                                        {{ amazon.amazon.fba_code }}
                                                    </option>
                                                {% endfor %}
                                            </select>
                                        </td>
                                        <td>
                                            <input class=" form-control" id="volume{{ forloop.counter0 }} " name="volume{{ forloop.counter0 }}"
                                                   value="{{ w_volume }}"
                                                   placeholder="体积" type="text" oninput="limit_Decimal_2(this)"
                                                   required />
                                        </td>
                                        <td>
                                            <input class=" form-control" id="weight{{ forloop.counter0 }} " name="weight{{ forloop.counter0 }}"
                                                   value="{{ w_weight }}"
                                                   placeholder="重量" type="text" oninput="limit_Decimal_2(this)"
                                                   required />
                                        </td>
                                        <td>
                                            <button type="button" id="add_warehouse", class="btn btn-danger " onclick="deleteCurrentRow(this)">
                                                <span class="glyphicon glyphicon-minus-sign"></span>
                                                删除仓库
                                            </button>
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                        {% if error_msg %}
                            <label class="text-left text-danger">{{ error_msg }}</label>
                        {% else %}
                            <label class="text-left"></label>
                        {% endif %}
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block myscript %}
    <script type="text/javascript">
        $('#warehouse_table select').amsifySelect({
            classes: {
                    clear : 'btn btn-danger',
                    close : 'btn btn-primary'
                }
        });

        // 新增仓库用
        {#$('#fba_code0').amsifySelect({#}
        {#    classes: {#}
        {#            clear : 'btn btn-danger',#}
        {#            close : 'btn btn-primary'#}
        {#        }#}
        {#});#}

    </script>
    <script type="text/javascript">
        //如果有输入， 清除错误提示
         $("#fba_number").bind('input propertychange', function () {
             $('#fba_number_fail').html('')
         })

         $("#hs_code_number").bind('input propertychange', function () {
             $('#hs_code_number_fail').html('')
         })


		let num=document.getElementById("warehouse_table").rows.length-2;
        /* 添加行 */
        const add_btn = document.getElementById("add_warehouse");
        const max_number = 9
        function appendRow(){
            if (num < max_number) {
                num++;
                console.log('add after num = '+num)
                const trHTML = '<tr> <td>' +
                    '<select id="fba_code' + num + '" name="fba_code' + num + '"' +
                    ' class="form-control" style="margin-right: 20px" searchable>' +
                    '<option value= "">选择需要派送的仓库代码</option>' +
                    '   {% for amazon in amazon_warehouse %}' +
                        '       <option value= {{ amazon.amazon }}> ' +
                        '{{ amazon.amazon }}'  +
                        '</option>' +
                        '{% endfor %}' +
                    '</select>' +
                    '</td>' +
                    '<td>' +
                    '<input class=" form-control" id="volume' + num + '"' + 'name="volume' + num + '"' +
                    'value="" placeholder="体积" type="text"' +
                    'oninput="limit_Decimal_2(this)" required />' +
                    '</td>' +
                    '<td>' +
                    '<input class=" form-control" id="weight' + num + '"' + 'name="weight' + num + '"' +
                    'value="" placeholder="重量" type="text"' +
                    'oninput="limit_Decimal_2(this)" required />' +
                    '</td>' +
                    '<td>' +
                    '<button type="button" id="del_warehouse", class="btn btn-danger " onclick="deleteCurrentRow(this)">' +
                    '<span class="glyphicon glyphicon-minus-sign"></span>' +
                    ' 删除仓库' +
                    '</button>' +
                    '</td></tr>' +
                    '<script type="text/javascript"> ' +
                    '$("#warehouse_table select").amsifySelect({' +
                    'classes: {' +
                    'clear : "btn btn-danger",' +
                    'close : "btn btn-primary"' +
                    '}' +
                    '})<' + '/script>';

                $("#warehouse_table").append(trHTML);
                if (num === max_number){
                    add_btn.disabled = true;  // 新增按钮设置为不可用
                }
            }
            else {
                add_btn.disabled = true;  // 达到10行后，新增按钮设置为不可用
              }
        }

      /* 删除行 */
      function deleteCurrentRow(obj) {
          obj.parentNode.parentNode.remove();   //  jQuery 对象删除当前行

          //===================================================
          num--;
          add_btn.disabled = false;  //重置新增按钮
      }
    </script>

{% endblock %}

ocean/templates/fba/ocean_fba_quotation.html
{% extends 'ocean_base.html' %}
{% load static %}

{% block new_content %}
    <!--main content start-->
<div class="">
    <div class="invoice-body">
        <div class="pull-left">
          <h2>海运散货FBA询价单</h2>
        </div>
        <!-- /pull-left -->
        <div class="pull-right ">
            <img src="{% static 'images/dd_logo.png' %}" alt="点达科技", width="200px" height="80px">
        </div>
        <!-- /pull-right -->
        <div class="clearfix"></div>
        <br>
        <div class="row">
            <div class="col-md-9">
                <h4>询价数据</h4>
                <address>
                    提货地点：<strong>{{ input_data.port }}</strong><br>
                    清关HS Codes数量： <strong>{{ input_data.hs_code_number }}</strong><br>
                    FBA 数量： <strong>{{ input_data.fba_number }}</strong><br>
                    {% if input_data.first_delivery == '1' %}
                        头程自行安排
                    {% endif %}
                </address>
          </div>
          <!-- /col-md-9 -->
          <div class="col-md-3">
            <div>
                <!-- /col-md-3 -->
                <div class="pull-left"> 询价编号: </div>
                <div class="text-right">{{ result_data.quote_ref_no }}</div>
                <div class="pull-left"> 询价时间: </div>
                <div class="text-right">{{ result_data.quote_time }}</div>
                <div class="clearfix"></div>
            </div>
            <!-- /row -->
            <br>
            <div class="well well-small green">
                <div class="pull-left"> 费用总计 : </div>
                <div class="pull-right">£{{ result_data.total_amount|floatformat:2 }}</div>
                <div class="clearfix"></div>
            </div>
          </div>
          <!-- /invoice-body -->
        </div>
        <!-- /col-lg-10 -->
        <table class="table">
          <thead>
            <tr>
              <th style="width:5%" class="text-center">序号</th>
              <th style="width:30%" class="text-left">收费项目</th>
              <th style="width:50%" class="text-left">备注说明</th>
              <th style="width:10%" class="text-right">金额</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-center">1</td>
              <td>清关费(Customs Clearance)</td>
              <td class="text-left">此清关费，含三个品名的费用</td>
              <td class="text-right">£{{ result_data.customs_clearance|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">2</td>
              <td>额外品名附加费(Extra Codes Surcharge)</td>
              <td class="text-left">从第四个品名开始计费</td>
              <td class="text-right">£{{ result_data.extra_codes|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class="text-center">3</td>
              <td>税金代缴手续费(Use of Deferment)</td>
              <td class="text-left">税金代缴费用为应缴进口duty&VAT的2%， 最低收费 £35.00</td>
              <td class="text-right">£{{ result_data.tax|floatformat:2 }}</td>
            </tr>
            {% if input_data.first_delivery == '1' %}
                <tr>
                  <td class="text-center">4</td>
                  <td>操作费(3rd party co-loader handling fee)</td>
                  <td class="text-left">头程自行安排在英国监管仓，我司只安排提货，需加收操作费</td>
                  <td class="text-right">£{{ result_data.handling_fee|floatformat:2 }}</td>
                </tr>
                <tr>
                  <td class="text-center">5</td>
                  <td>亚马逊预约费(FBA Booking Fee)</td>
                  <td class="text-left"></td>
                  <td class="text-right">£{{ result_data.booking_fee|floatformat:2 }}</td>
                </tr>
                {% for warehouse in result_data.warehouse_data %}
                    <tr>
                      <td class="text-center">{{ forloop.counter0|add:"6" }}</td>
                      <td>派送费(Delivery Fee) - 仓库代码：{{ warehouse.0 }}</td>
                      <td class="text-left">体积: {{ warehouse.1 }} 立方米</td>
                      <td class="text-right">£{{ warehouse.2 }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                  <td class="text-center">4</td>
                  <td>亚马逊预约费(FBA Booking Fee)</td>
                  <td class="text-left"></td>
                  <td class="text-right">£{{ result_data.booking_fee|floatformat:2 }}</td>
                </tr>
                {% for warehouse in result_data.warehouse_data %}
                    <tr>
                      <td class="text-center">{{ forloop.counter0|add:"5" }}</td>
                      <td>派送费(Delivery Fee) - 仓库代码：{{ warehouse.0 }}</td>
                      <td class="text-left">体积: {{ warehouse.1 }} 立方米  重量: {{ warehouse.2 }} 公斤</td>
                      <td class="text-right">£{{ warehouse.3 }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
            <tr>
              <td colspan="3" class="text-right no-border">
                <div class=""><strong>费用合计：</strong></div>
              </td>
              <td class="text-right"><strong>£{{ result_data.total_amount|floatformat:2 }}</strong></td>
            </tr>
            <tr>
              <td ></td>
              <td colspan="2" class="text-right no-border">
                <div><strong></strong>英镑/人民币汇率：¥1.00 = £{{ result_data.exchange_rate|floatformat:4 }} (请注意  该汇率仅作为参考，实际结算汇率以下单当天汇率为准)
                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>人民币合计：</strong></span></div>
              </td>
              <td class="text-right"><strong>¥{{ result_data.total_rmb|floatformat:2 }}</strong></td>
            </tr>
          </tbody>
        </table>
        <h4>其它条款</h4>
        <p>感谢你的支持，本报价为实时报价，价格由于变化比较快，以实际下单为准。PS: 监管仓堆存费实报实销</p>
        <br>
        <br>
        <a type="button" id="add_address" href="{% url 'ocean:ocean_fba' %}" class="btn btn-primary pull-left">
            重新查询
        </a>
        <button type="button" class="btn btn-info pull-right" data-toggle="modal"
                data-target="#myModal-Surcharge" style="float:left; margin-left: 10px">其它附加费说明</button>
        <br>
        <br>
    </div>
</div>
<div class="modal fade" id="myModal-Surcharge" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            {% include 'fba/ocean_fba_surcharge.html' %}
        </div>
    </div>
</div>
{% endblock %}